modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"

[[mods]]
modId="battlemage"
version="2.2.1-1.18.2"
displayName="Battlemage"
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
logoFile="examplemod.png"
credits=""
authors="AradorYin"
description='''
This mod brings the systems seen in Lichdom: Battlemage to Minecraft.
'''

[[dependencies.battlemage]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.battlemage]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"
